# Generated by Django 4.2.1 on 2023-05-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': '할일등록', 'verbose_name_plural': '할일등록'},
        ),
    ]
