# Generated by Django 4.2.1 on 2023-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='attached',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d', verbose_name='attached'),
        ),
    ]
