# Generated by Django 4.2.1 on 2023-05-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_myinfo_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='double_major',
            field=models.CharField(default='', max_length=50),
        ),
    ]
