# Generated by Django 4.2.1 on 2023-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_myinfo_double_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
    ]
