# Generated by Django 4.2.1 on 2023-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_myinfo_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
