# Generated by Django 4.2.1 on 2023-05-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_myinfo_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('lecture_code', models.CharField(max_length=50, verbose_name='강의코드')),
                ('lecture_name', models.CharField(max_length=50, verbose_name='강의명')),
                ('semester', models.CharField(blank=True, max_length=50, verbose_name='학기')),
                ('category', models.CharField(max_length=32, verbose_name='강의구분')),
                ('status', models.CharField(choices=[('normal', '강의개설중'), ('over', '강의만석'), ('exit', '강의폐강')], default='normal', max_length=8, verbose_name='상태(status)')),
                ('campus', models.CharField(choices=[('normal', '강의개설중'), ('over', '강의만석'), ('exit', '강의폐강')], default='gajwa', max_length=8, verbose_name='캠퍼스')),
                ('e_learning', models.CharField(max_length=32, verbose_name='원격수업')),
                ('credit', models.CharField(max_length=32, verbose_name='강의학점')),
                ('professor', models.CharField(max_length=32, verbose_name='교수명')),
                ('week', models.CharField(max_length=32, verbose_name='요일')),
                ('lecture_time', models.CharField(max_length=50, verbose_name='강의시간')),
                ('lecture_room', models.CharField(default='', max_length=50, verbose_name='강의실')),
                ('department', models.CharField(default='', max_length=50, verbose_name='건물명')),
                ('desciption', models.CharField(default='', max_length=50, verbose_name='설명')),
            ],
            options={
                'verbose_name': '강의실정보',
                'verbose_name_plural': '강의실정보',
            },
        ),
    ]
