# Generated by Django 4.2.1 on 2023-05-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lectureinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='grade',
            field=models.CharField(default='', max_length=32, verbose_name='학년'),
        ),
        migrations.AddField(
            model_name='lectureinfo',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='상세구분'),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='campus',
            field=models.CharField(choices=[('gajwa', '가좌캠퍼스'), ('tongyeong', '통영캠퍼스')], default='gajwa', max_length=20, verbose_name='캠퍼스'),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='category',
            field=models.CharField(max_length=50, verbose_name='강의구분'),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lecture_code',
            field=models.CharField(max_length=30, verbose_name='강의코드'),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='semester',
            field=models.CharField(blank=True, max_length=32, verbose_name='학기'),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='status',
            field=models.CharField(choices=[('normal', '강의개설중'), ('over', '강의만석'), ('exit', '강의폐강')], default='normal', max_length=15, verbose_name='상태(status)'),
        ),
    ]
