# Generated by Django 4.2.1 on 2023-05-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lectureinfo_grade_lectureinfo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureinfo',
            name='desciption',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='e_learning',
            field=models.CharField(blank=True, max_length=32, verbose_name='원격수업'),
        ),
    ]
