# Generated by Django 4.2.1 on 2023-05-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_is_admin_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('normal', '재학중'), ('absence', '휴학중'), ('exit', '졸업')], default='normal', max_length=8, verbose_name='상태(status)'),
        ),
    ]
